/**
 * init-templates.test.ts — golden-output tests for scripts/init-templates/.
 *
 * Renders each template via `bin/gstack-extend init` against a tmpdir, then
 * asserts on the rendered content (no full file snapshots — those would
 * churn on every test_cmd_block tweak). Also covers per-language detection
 * by salting the target with a manifest before init runs.
 */

import { afterAll, describe, expect, test } from 'bun:test';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { makeBaseTmp } from './helpers/fixture-repo.ts';
import { mkScope } from './helpers/init-scope.ts';
import { runBin } from './helpers/run-bin.ts';

const ROOT = join(import.meta.dir, '..');
const BIN = join(ROOT, 'bin', 'gstack-extend');

const baseTmp = makeBaseTmp('init-tmpl-');
afterAll(() => {
  try { rmSync(baseTmp, { recursive: true, force: true }); } catch {}
});

function scope(name: string, manifest?: { file: string; content: string }) {
  const scoped = mkScope(baseTmp, name);
  if (manifest) {
    mkdirSync(scoped.target, { recursive: true });
    writeFileSync(join(scoped.target, manifest.file), manifest.content);
  }
  return scoped;
}

function init(scope_: ReturnType<typeof scope>, extra: string[] = []) {
  return runBin(BIN, ['init', scope_.target, '--no-prompt', ...extra], {
    home: scope_.home,
    gstackExtendDir: ROOT,
    gstackExtendStateDir: scope_.state,
    extraEnv: { GSTACK_STATE_ROOT: scope_.groot },
  });
}

describe('template substitution', () => {
  test('CLAUDE.md substitutes name and created_at; no leftover {{vars}}', () => {
    const s = scope('claude');
    const r = init(s);
    expect(r.exitCode).toBe(0);
    const claude = readFileSync(join(s.target, 'CLAUDE.md'), 'utf8');
    expect(claude).toContain('# target');
    expect(claude).toMatch(/scaffold generated by `gstack-extend init` on \d{4}-\d{2}-\d{2}T/);
    expect(claude).not.toMatch(/\{\{[a-zA-Z_]+\}\}/);
  });

  test('VERSION renders to 0.0.0.0', () => {
    const s = scope('version');
    init(s);
    expect(readFileSync(join(s.target, 'VERSION'), 'utf8').trim()).toBe('0.0.0.0');
  });

  test('ROADMAP.md has all four state sections in canonical order', () => {
    const s = scope('roadmap');
    init(s);
    const md = readFileSync(join(s.target, 'docs', 'ROADMAP.md'), 'utf8');
    const inProgressIdx = md.indexOf('## In Progress');
    const currentIdx = md.indexOf('## Current Plan');
    const futureIdx = md.indexOf('## Future');
    const shippedIdx = md.indexOf('## Shipped');
    expect(inProgressIdx).toBeGreaterThan(-1);
    expect(currentIdx).toBeGreaterThan(inProgressIdx);
    expect(futureIdx).toBeGreaterThan(currentIdx);
    expect(shippedIdx).toBeGreaterThan(futureIdx);
    expect(md).toContain('Deferred: docs/roadmap-future.md (0 items)');
    expect(md).toContain('History: docs/roadmap-shipped.md');
  });

  test('init writes empty Future and Shipped satellite files', () => {
    const s = scope('satellites');
    init(s);
    const future = readFileSync(join(s.target, 'docs', 'roadmap-future.md'), 'utf8');
    const shipped = readFileSync(join(s.target, 'docs', 'roadmap-shipped.md'), 'utf8');
    expect(future).toContain('## Future');
    expect(shipped).toContain('## Shipped');
  });

  test('TODOS.md seeds first-session checklist with [manual] tag', () => {
    const s = scope('todos');
    init(s);
    const md = readFileSync(join(s.target, 'docs', 'TODOS.md'), 'utf8');
    expect(md).toContain('## Unprocessed');
    expect(md).toContain('### [manual] First-session checklist');
    expect(md).toContain('/roadmap');
    expect(md).toContain('/review-apparatus');
    expect(md).toContain('/full-review');
  });

  test('PROGRESS.md has a version-history table with 0.0.0.0 row', () => {
    const s = scope('progress');
    init(s);
    const md = readFileSync(join(s.target, 'docs', 'PROGRESS.md'), 'utf8');
    expect(md).toContain('| 0.0.0.0 |');
    expect(md).toContain('Project scaffolded by `gstack-extend init`');
  });

  test('CHANGELOG.md renders at root, not docs/', () => {
    const s = scope('changelog');
    init(s);
    const md = readFileSync(join(s.target, 'CHANGELOG.md'), 'utf8');
    expect(md).toContain('[0.0.0.0]');
    expect(md).toContain('Initial project scaffold');
  });
});

describe('per-language detect → test_cmd_block', () => {
  test('package.json → bun run test', () => {
    const s = scope('lang-bun', { file: 'package.json', content: '{"name":"x"}' });
    init(s);
    expect(readFileSync(join(s.target, 'CLAUDE.md'), 'utf8')).toContain('bun run test');
  });

  test('Cargo.toml → cargo test', () => {
    const s = scope('lang-cargo', { file: 'Cargo.toml', content: '[package]\nname="x"' });
    init(s);
    expect(readFileSync(join(s.target, 'CLAUDE.md'), 'utf8')).toContain('cargo test');
  });

  test('go.mod → go test ./...', () => {
    const s = scope('lang-go', { file: 'go.mod', content: 'module x' });
    init(s);
    expect(readFileSync(join(s.target, 'CLAUDE.md'), 'utf8')).toContain('go test ./...');
  });

  test('pyproject.toml → pytest', () => {
    const s = scope('lang-python', { file: 'pyproject.toml', content: '[project]\nname="x"' });
    init(s);
    expect(readFileSync(join(s.target, 'CLAUDE.md'), 'utf8')).toContain('pytest');
  });

  test('no manifest → TODO line in CLAUDE.md', () => {
    const s = scope('lang-unknown');
    init(s);
    const md = readFileSync(join(s.target, 'CLAUDE.md'), 'utf8');
    expect(md).toContain('TODO: define the project test command');
  });
});

describe('language precedence', () => {
  const commands = {
    bun: 'bun run test',
    cargo: 'cargo test',
    go: 'go test ./...',
    python: 'pytest',
    unknown: 'TODO: define the project test command',
  };
  const rows: Array<{ name: string; files: string[]; expect: keyof typeof commands }> = [
    { name: 'all', files: ['package.json', 'Cargo.toml', 'go.mod', 'pyproject.toml', 'requirements.txt'], expect: 'bun' },
    { name: 'no-package', files: ['Cargo.toml', 'go.mod', 'pyproject.toml', 'requirements.txt'], expect: 'cargo' },
    { name: 'no-cargo', files: ['go.mod', 'pyproject.toml', 'requirements.txt'], expect: 'go' },
    { name: 'no-go', files: ['pyproject.toml', 'requirements.txt'], expect: 'python' },
    { name: 'requirements-only', files: ['requirements.txt'], expect: 'python' },
    { name: 'none', files: [], expect: 'unknown' },
  ];

  test.each(rows)('$name selects $expect and omits the other commands', (row) => {
    const s = scope(`precedence-${row.name}`);
    if (row.files.length > 0) mkdirSync(s.target, { recursive: true });
    for (const file of row.files) writeFileSync(join(s.target, file), 'x\n');
    const r = init(s);
    expect(r.exitCode).toBe(0);
    const md = readFileSync(join(s.target, 'CLAUDE.md'), 'utf8');
    expect(md).toContain(commands[row.expect]);
    for (const [lang, command] of Object.entries(commands)) {
      if (lang !== row.expect) expect(md).not.toContain(command);
    }
  });
});
