#!/usr/bin/env bash
#
# regen-source-tag-corpus.sh — regenerate tests/fixtures/source-tag-hash-corpus.json.
#
# Walks a curated input list, runs bin/lib/source-tag.sh::compute_dedup_hash on
# each, writes the result to a JSON fixture with a manifest header recording
# bash version, OS, locale, and the byte-input contract. The TS port asserts
# byte-for-byte parity against this fixture.
#
# Why a regenerator: the fixture is folklore without provenance. Anyone who
# regenerates it on a different machine must record the environment so
# divergences are traceable. The TS port uses Buffer.from(normalized, 'utf8')
# to match `printf '%s' "$normalized"` byte semantics — that contract is
# documented in the manifest header below.
#
# Usage:
#   ./scripts/regen-source-tag-corpus.sh
#
# Output:
#   tests/fixtures/source-tag-hash-corpus.json (overwritten)

set -euo pipefail

# Force LC_ALL=C so [:upper:] / [:lower:] / [:punct:] in bin/lib/source-tag.sh's
# `tr` and `sed` calls produce ASCII-only character classes — matches the TS
# port's asciiLower / ASCII_PUNCT_RE / ASCII_WS_RUN_RE byte-for-byte. Without
# this, regenerating the corpus on a non-C locale could embed locale-dependent
# hashes that the TS port can never reproduce.
export LC_ALL=C

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

# shellcheck source=../bin/lib/source-tag.sh
source "$REPO_ROOT/bin/lib/source-tag.sh"

OUT="$REPO_ROOT/tests/fixtures/source-tag-hash-corpus.json"

# JSON-escape a string. Handles backslash, double-quote, control chars, and
# Unicode outside ASCII via \uXXXX. Uses python3 (ships everywhere we run);
# pure-bash JSON escaping isn't worth the complexity for this corpus.
json_escape() {
  python3 -c 'import json, sys; sys.stdout.write(json.dumps(sys.argv[1]))' "$1"
}

# Curated adversarial corpus inputs. Order is stable; entries have categories
# in the comment trailer for easy auditing. Excludes NUL bytes and invalid
# UTF-8 (don't round-trip through JSON cleanly per docs/designs/bun-test-architecture.md
# review).
INPUTS=(
  # Plain ASCII (variety)
  "Simple title"
  "Multi-word bug fix"
  "edge-case in parser"
  "Regression: foo()"
  "A"

  # Trailing-metadata sentinels
  "Bug X — Found on branch kbitz/foo"
  "Bug X Found on branch kbitz/foo"
  "Bug Y (2026-04-23)"
  "Feature Z (v0.9.21)"
  "Crash Source: [pair-review:group=2]"
  "NSNull crash in reply composer"
  "NSNull crash in reply composer — Found on branch kbitz/threading (2026-04-20)"

  # Unicode em-dash, quotes, smart apostrophe
  "Title—with—em—dashes"
  "“Smart quoted bug”"
  "Don’t panic"

  # Non-Latin scripts
  "京都の バグ"
  "Ошибка в парсере"
  "خطأ في التحليل"

  # Zero-width / boundary
  "trim me"
  "MULTIPLE    SPACES"

  # Edge boundaries
  ""
  "x"

  # Internal whitespace control chars — these are the exact bytes bash preserves
  # via tr -s squeeze semantics. The corpus locks the bash↔TS parity contract
  # for inputs LLMs may produce when copy-pasting multi-line content.
  $'one\ttwo'
  $'line1\nline2'
  $'a\tb\tc'
  $'a-\tb'
  $'tab\t\trun'
  $'cr\rin'
  $'mixed \t \nws'
)

# Build long title programmatically (>1024 chars) outside the array literal so
# the array stays readable.
LONG_TITLE=$(python3 -c "print('lorem ipsum ' * 100)")
INPUTS+=("$LONG_TITLE")

# Capture environment metadata for the manifest header.
BASH_VERSION_LINE=$(bash --version 2>/dev/null | head -1 || echo "unknown")
UNAME_LINE=$(uname -sr)
LOCALE_LINE=$(locale 2>/dev/null | grep -E '^LC_ALL|^LANG' | tr '\n' ' ' || echo "unknown")
GENERATED_AT=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Begin JSON output. Manifest first.
{
  echo "{"
  echo "  \"\$comment\": \"Generated by scripts/regen-source-tag-corpus.sh — do not hand-edit. Run the script to regenerate.\","
  echo "  \"generator\": \"bin/lib/source-tag.sh::compute_dedup_hash\","
  echo "  \"generator_command\": \"printf '%s' \\\"\$normalized\\\" | shasum -a 1 | cut -c1-12\","
  echo "  \"bash_version\": $(json_escape "$BASH_VERSION_LINE"),"
  echo "  \"uname\": $(json_escape "$UNAME_LINE"),"
  echo "  \"locale\": $(json_escape "$LOCALE_LINE"),"
  echo "  \"encoding\": \"utf-8 (printf '%s' semantics; no trailing newline)\","
  echo "  \"ts_input_contract\": \"crypto.createHash('sha1').update(Buffer.from(normalized, 'utf8')).digest('hex').slice(0, 12)\","
  echo "  \"generated_at\": \"$GENERATED_AT\","
  echo "  \"fixtures\": ["
} > "$OUT"

# Walk inputs, write each fixture entry.
LAST_IDX=$((${#INPUTS[@]} - 1))
for i in "${!INPUTS[@]}"; do
  raw="${INPUTS[$i]}"
  hash=$(compute_dedup_hash "$raw")
  if [ "$i" -lt "$LAST_IDX" ]; then
    sep=","
  else
    sep=""
  fi
  printf '    { "input": %s, "expected_hash": "%s" }%s\n' \
    "$(json_escape "$raw")" "$hash" "$sep" >> "$OUT"
done

# Close JSON.
{
  echo "  ]"
  echo "}"
} >> "$OUT"

echo "Wrote $OUT ($((${#INPUTS[@]})) fixtures)"
